### ISSUE TITLE
Research impact of migration in the infrastructure-bundle

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/newrelic-coreint#137]
Modify the infrastructure-bundle on staging removing definition files and modifying configs and test updating it as a user to see which implications it has, including on-host ECS monitoring.

**Comment by paologallinaharbur** [comment]
Regarding:
 - K8s: Autodiscovery is available from config V4 on, therefore even if it is possible that a user is mounting manually a V3 config in the container in K8s would lead to duplicate data and it is not recommended
 - nri-ecs: Autodiscovery is available from config V4 on, moreover V4 is always advised in the examples
 - standalone in docker(no idea how common is this scenario): It is definitely possible that different users rely on that since all the integrations had V3 config sample and the definition was there.

Removing those files could represent a breaking change for all those users.

Even if it is not common, some user might still be using the definition file. Since we decided to kept it for legacy compatibility when installing integration, I advice to do the same in this case

**Comment by paologallinaharbur** [comment]
The k8s integration has been modified to use V4, on the other hand nri-ecs was already using V4.

All definition files have been updated already with a comment specifying that they are legacy

**Comment by paologallinaharbur** [comment]
The risk is actually really low, however the benefit we get from removing them is really low as well (it is useful mainly to clean away some useless files).
