### ISSUE TITLE
Migrate and release samples to v4, whenever possible

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/newrelic-coreint#138]
Once investigated implications, migrate all samples on the integrations and their releases to V4:

## Pending integrations

- [x] nri-nginx **Released**
- [x] nri-redis  **Released**
- [x] nri-apache  **Released**
- [x] nri-mysql  **Released**
- [x] nri-kafka **Released**
- [x] nri-mssql  **Released**
- [x] nri-oracledb  **Released**
- [x] nri-elasticsearch **Released**
- [x] nri-mongodb **Released**
- [x] nri-cassandra **Released**
- [x] nri-consul **Released**
- [x] nri-couchbase **Released**
- [x] nri-f5 **Released**
- [x] nri-haproxy  **Released**
- [x] nri-memcached  **Released**
- [x] nri-nagios   **Released**
- [x] nri-postgresql **Released**
- [x] nri-rabbitmq **Released**
- [x] nri-varnish **Released**
- [x] nri-kubernetes  Prereleased
- [x] nri-jmx  Prereleased
- [x] nri-snmp  Prereleased

**PRs will need to be updated with the agent dependency once Caos releases the fix**

**Comment by roobre** [comment]
There are several ways to set configuration in v4, at least two that I'm aware of: the `env` section and the `config` section. It would be nice to explore both options and decide which one will be best.

**Comment by paologallinaharbur** [comment]
@alvarocabanas 
 - As part of this task are we updating as well the wix project for each integration?
 - Are we going to require a minumum version of the agent? Es (1.13.0)

**Comment by paologallinaharbur** [comment]
- We checked and updating the wix project is not needed!
 - Regarding the minimum version required we are going to set up the latest version of the agent available once the EnvVar Pr is merged.

```
  deb:
    depends:
      - baz (>= 1.2.3-0)
      - some-lib-dev
    # ...
  rpm:
    depends:
      - baz >= 1.2.3-0
      - some-lib-devel
```

Sadly this is not going to be available for Windows users since dependencies are -not- supported. For updating the integration and agent update is not needed, on the other hand on fresh install updating the agent could be needed
