### ISSUE TITLE
Research limitations of migration script

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/newrelic-coreint#142]
Research and create an automatic transformer or a user executed tool that, given an integration in V3 config, transforms the config to V4 and tells the agent to be restarted.

We should make a big research step here, as well as some UX concerns.

The v4 protocol has many features that might be hard to work with from an automigration script:

- Databind (gathering values from discoveries/secret providers)
- Environment variables placeholders in the config file
- Running conditions
- Integration commands, as opposed to arguments
- Overrides to the exec lines.
- Custom integrations
- Yaml comments the user has put in the config file

If we go with the option of offering a tool that performs this migration, but non automatically: It could show the user both files, old and new, and allows them to make changes there.

**Comment by paologallinaharbur** [comment]
I am timeboxing it since I am not sure we can provide something to do that automatically covering all different cases.

At least we should be able to have something to migrate the manifest we own, even if that is a one-time task

**Comment by paologallinaharbur** [comment]
The main limitation are:
 - the possibility to have a relative path in the old config and not in the new one. Notice that this is not that frequent since most of users will have the integration installed in the standard locations (possibly breaking)
 - all comments are lost. The old config is added as well as a comment (not beaking)
 - Order of args is changed (not breaking)

Creating the new config and delete the old one automatically could represent a risk, the best option would be to scan a whole folder, migrate all samples adding a `.migrated` suffix and leave the decision of migrating to the user.

The is a working example in the CLI performing such transformation. We can decide if we want to release this (improving the code, adding tests etc) or not.
https://github.com/newrelic/newrelic-cli/compare/main...paologallinaharbur:pgallina/migrationv3v4?expand=1

**Comment by paologallinaharbur** [comment]
Moreover we noticed that in multiline yaml transform automatically `>-` to `|-` that is not exactly the same https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
