### ISSUE TITLE
Improve Docs on K8S ECS autodiscovery

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/newrelic-coreint#19]
The docs regarding monitoring integrations over ECS and K8s should be review as a whole.
Currently we have two docs page helping to do that:
 - https://docs.newrelic.com/docs/integrations/kubernetes-integration/link-apps-services/monitor-services-running-kubernetes for K8s
 - https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/monitor-services-running-amazon-ecs/ for ECS
 
Their positions in the docs is confusing (one inside k8s documentation and the second one under on host integrations)
Moreover in the repos in github do not have any hint regarding how to setup an integration for ECS and no tutorial showing step to step how to do it.

We should add samples to the different integrations repos

I also believe that confusion rises since in standard installation we use config format V3 and in K8s V4 (even if in the bundle the definition file is packaged anyway and if that is not intended we should remove them)

**Comment by paologallinaharbur** [comment]
Actually there is one example regarding how to configure ECS that is wrong in the autodiscovery section: https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery-host-integrations/

[More context](https://newrelic.slack.com/archives/CP2EWSX7C/p1617730043136800)

**Comment by bpschmitt** [comment]
@paologallinaharbur I'm working on an example NGINX docker config.  

We should consider documenting the `METRICS` and `REMOTE_MONITORING` env variables or changing how they're configured.  I assume this is essentially the same as providing the `-metrics` and `-remote_monitoring` flags to the `nri-nginx` binary?  

Also, it's not clear what the `-metrics` vs. `-events` flags do.  I believe these are pretty standard for all OHIs.  Why would I want to use one instead of the other?

https://github.com/bpschmitt/nri-nginx/blob/docker-config-update/nginx-config.yml.docker_sample#L21

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
